# https://qiita.com/otanu/items/98d553d4b685a8419952
# 後で書いてdocker-composeで立ち上げられるようにする
# Docker導入後はlocalhostではなく環境変数注入して対応
FROM  node:10.12.0-slim

WORKDIR /client
COPY . .
RUN yarn install
CMD ["yarn", "start"]
EXPOSE 3000